브로드 캐스팅
- 두 배열의 차원의 크기가 같다 -> 그냥 계산
- 두 배열의 차원이 다르고 한 배열의 차원이 1차원(벡터)
- 차원을 늘렸을 때 계산이 가능한 경우!

### 난수 생성 함수

random

In [1]:
import numpy as np

In [4]:
a = np.random.rand(2, 2) # 0 ~ 1 사이에 값 랜덤
print(a)

[[0.47584113 0.36531459]
 [0.98174779 0.55823631]]


In [5]:
b = np.random.randn(2, 2) # 평균이 0, 분산이 1: 표준 정규 분포
print(b)

[[-0.62176205  0.38936396]
 [ 0.13256806  0.49533295]]


In [15]:
c = np.random.randint(0, 10, size=5) # 랜덤한 정수값 생성
print(c)

[3 8 5 5 6]


In [9]:
c2 = np.random.randint(0, 10, size=(2, 2)) # 랜덤한 정수값 생성
print(c2)

[[1 8]
 [7 1]]


In [18]:
import numpy as np

In [28]:
d = np.arange(5) # 0 ~ 9까지 값을 생성 0 ~ 4: 5 개
np.random.shuffle(d) # 복사본 생성이 x, 원본 값이 변한다.
print(d)

[0 3 4 2 1]


In [30]:
# choice = np.random.choice(d, 5) # 중복을 허용
# choice = np.random.choice(d, 5, replace=False) # 중복을 허용하지 않는다.
choice = np.random.choice(d, 5, p=[0, 0.4, 0.2, 0.3, 0.1])
# p값을 100%(1)로 설정해야 합니다.
print(choice)

[1 1 0 0 0]


In [34]:
# permutation 순열 -> 수정해서 파일 전해드림
a = np.arange(10)
a_p = np.random.permutation(a)
print(a_p)
print(a)

[5 3 1 8 0 4 9 2 6 7]
[0 1 2 3 4 5 6 7 8 9]


In [35]:
# 정규분포를 따르는 난수 생성
# a = np.random.normal('평균', '표준편차', '갯수')
a = np.random.normal(0, 1, 3)
print(a)

[ 1.60507894  0.23073598 -1.52881098]


# Pandas

- 데이터 자체를 분석, 파악
- 표
- 데이터 다루는 데 초점
- 정렬, 필터링, 그룹화, 집계

- 데이터 로딩 및 저장
- 데이터 인덱싱 및 슬라이싱
- 결측치 처리
- 데이터 변환
- 데이터 집계 및 그룹화
---
- 시계열 데이터 처리
- 데이터 시각화


## 1. Series(시리즈)
- 인덱스를 지정할 수 있음

In [36]:
import pandas as pd

In [38]:
s = pd.Series([1, 2, 3, 4]) # 리스트
print(s)

0    1
1    2
2    3
3    4
dtype: int64


In [39]:
s2 = pd.Series({'a': 1, 'b':2, 'c':3, 'd': 4}) # 딕셔너리
print(s2)

a    1
b    2
c    3
d    4
dtype: int64


In [40]:
s3 = pd.Series(5, index=[0, 1, 2]) # 스칼라
print(s3)

0    5
1    5
2    5
dtype: int64


In [41]:
data = [1, 2, 3, 4, 5]
index = ['a', 'b', 'c', 'd', 'e']
series = pd.Series(data, index=index) # 활용
print(series)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [42]:
s = pd.Series(data)
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64


### 슬라이싱

In [46]:
data = [1, 2, 3, 4, 5]
series = pd.Series(data)

In [47]:
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [48]:
series[0]

1

In [50]:
series[0:4]

0    1
1    2
2    3
3    4
dtype: int64

In [51]:
series[:4]

0    1
1    2
2    3
3    4
dtype: int64

In [52]:
series[:-1]

0    1
1    2
2    3
3    4
dtype: int64

In [53]:
series[::-1]

4    5
3    4
2    3
1    2
0    1
dtype: int64

In [54]:
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


#### Boolean indexing


In [55]:
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [56]:
print(series > 2)

0    False
1    False
2     True
3     True
4     True
dtype: bool


In [57]:
print(series[series > 2]) # a[a조건]

2    3
3    4
4    5
dtype: int64


In [58]:
# 5보다 작은 시리즈 만들기
print(series[series < 5])

0    1
1    2
2    3
3    4
dtype: int64


### Series 산술연산

In [62]:
print(series + 100)
print(series - 100)
print(series * 100)
print(series ** 100)
print(series / 100)
print(series % 100)
print(series // 100)
# 곱하기: *, 제곱: **, 나누기(float 몫): /, 나머지: %, 나누기(int 몫): //

0    101
1    102
2    103
3    104
4    105
dtype: int64
0   -99
1   -98
2   -97
3   -96
4   -95
dtype: int64
0    100
1    200
2    300
3    400
4    500
dtype: int64
0                      1
1                      0
2   -2984622845537545263
3                      0
4   -3842938066129721103
dtype: int64
0    0.01
1    0.02
2    0.03
3    0.04
4    0.05
dtype: float64
0    1
1    2
2    3
3    4
4    5
dtype: int64
0    0
1    0
2    0
3    0
4    0
dtype: int64


0   -99
1   -98
2   -97
3   -96
4   -95
dtype: int64

## Series 객체에 접근
- keys -> index
- values

In [63]:
print(series.keys)
'''
<bound method Series.keys of
0    1
1    2
2    3
3    4
4    5
dtype: int64>
'''

<bound method Series.keys of 0    1
1    2
2    3
3    4
4    5
dtype: int64>


In [72]:
print(series.keys())
print(series.index)
print(series.values)

RangeIndex(start=0, stop=5, step=1)
RangeIndex(start=0, stop=5, step=1)
[1 2 3 4 5]


In [79]:
print(series[0])

1


In [71]:
s2 = pd.Series({'a': 1, 'b':2, 'c':3, 'd': 4}) # 딕셔너리
print(s2.keys())

Index(['a', 'b', 'c', 'd'], dtype='object')


In [67]:
s2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [74]:
print(s2)

a    1
b    2
c    3
d    4
dtype: int64


In [76]:
# items

print(s2.items()) # zip -> 순회가 가능, 쌍

In [77]:
for index, value in s2.items():
  print(f'인덱스: {index}, 데이터: {value}')

인덱스: a, 데이터: 1
인덱스: b, 데이터: 2
인덱스: c, 데이터: 3
인덱스: d, 데이터: 4


In [80]:
s = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])

In [81]:
print(s)

a    10
b    20
c    30
d    40
dtype: int64


In [83]:
print(s.loc['b']) # loc: 행에 접근 -> 레이블(특정 인덱스)에 접근하기 위해서
print(s.loc['b':'d'])

20
b    20
c    30
d    40
dtype: int64


In [84]:
print(s.iloc[1]) # iloc: (행에 기반한) 열에 접근

20


In [85]:
print(s.iloc[1:3])

b    20
c    30
dtype: int64


In [86]:
print(s.iloc[-1])

40


In [88]:
print(s)

a    10
b    20
c    30
d    40
dtype: int64


In [96]:
print(s.at['a']) # at loc 비슷, 하나의 값만 가져올 때

10


In [89]:
print(s.iat[0]) # at 에 기반

10


In [100]:
print(s.get('e', default=-1)) # 없을 때 값 처리 방법이 다름, error가 나지 않고 없다는 걸 알려줌

-1


In [101]:
import numpy as np

## 결측값 (NaN, None)

- isna()
- isnull()

NaN(Not a Number) -> float

None -> none

In [103]:
data = [1, 2, 3, None]

print(np.array(data))

[1 2 3 None]


In [104]:
print(pd.Series(data))

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64


In [106]:
s = pd.Series(data) # isna(), isnull()

print(s.isna())
print(s.isnull().sum())

0    False
1    False
2    False
3     True
dtype: bool
1


In [108]:
print(s.notnull().sum())

3


결측치 제거

In [109]:
s.dropna()

0    1.0
1    2.0
2    3.0
dtype: float64

In [111]:
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

결측치를 0을 치환

In [114]:
s.fillna(0)

0    1.0
1    2.0
2    3.0
3    0.0
dtype: float64

## series 함수

In [115]:
s = pd.Series([1, 3, 5, 7, 9])

In [116]:
s.count() # 카운트 함수

5

In [117]:
s.min() # 최소값

1

In [118]:
s.max() # 최대값

9

In [120]:
print(s.mean())
print(s.median())
print(s.std())
print(s.var())

5.0
5.0
3.1622776601683795
10.0


In [121]:
s.describe() # 기초 통계 내용

count    5.000000
mean     5.000000
std      3.162278
min      1.000000
25%      3.000000
50%      5.000000
75%      7.000000
max      9.000000
dtype: float64